### ISSUE TITLE
ruff formatter won't save changes made

### ISSUE THREAD

**Issue by kjaymiller** [kjaymiller/cookiecutter-relecloud#286]
ruff formatter is added to the github action... however there is no logic to persist the changes after they've been made.

I've created the logic before here - https://github.com/render-engine/render-engine/blob/ded3baeff9a584d0c494cf8cf7266fbebb004f0b/.github/workflows/lint.yml#L45C1-L54C11

but I'm not sure if the Azure-Samples policy will allow for commiting changes as it did require 

```yaml
permissions:
    contents: write
    pull-requests: write
```
